# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


app_a = Analysis(['app.py'],
             pathex=['C:\\Users\\Welaptega\\CMSv3\\app\\envs\\cms_env\\Lib\\site-packages',
                      'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\DLLs',
                      'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\lib',
                      'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38',
                      'C:\\Users\\Welaptega\\AppData\\Roaming\\Python\\Python38\\site-packages',
                      'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages'],
             binaries=[],
             datas=[('api/data/config', 'api/data/config'), ('api/project/last_project.json', 'api/project'),
                    ('api/data/projects', 'api/data/projects'), ('api/data/calib', 'api/data/calib'),
                    ('api/assets', 'api/assets'), ('api/data/app_data', 'api/data/app_data')],
             hiddenimports=['eventlet.hubs.epolls',
                            'eventlet.hubs.kqueue',
                            'eventlet.hubs.selects',
                            'dns',
                            'dns.dnssec',
                            'dns.e164',
                            'dns.hash',
                            'dns.namedict',
                            'dns.tsigkeyring',
                            'dns.update',
                            'dns.version',
                            'dns.zone'],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
app_pyz = PYZ(app_a.pure, app_a.zipped_data,
             cipher=block_cipher)

app_exe = EXE(app_pyz,
          app_a.scripts,
          [],
          exclude_binaries=True,
          name='app',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )

mc_a = Analysis(['api\\server\\measurement\\measurement_client.py'],
                pathex=['C:\\Users\\Welaptega\\CMSv3\\app\\envs\\cms_env\\Lib\\site-packages',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\DLLs',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\lib',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38',
                        'C:\\Users\\Welaptega\\AppData\\Roaming\\Python\\Python38\\site-packages',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
mc_pyz = PYZ(mc_a.pure, mc_a.zipped_data,
             cipher=block_cipher)

mc_exe = EXE(mc_pyz,
          mc_a.scripts,
          [],
          exclude_binaries=True,
          name='measurement_client',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )

cm_a = Analysis(['api\\server\\devices\\client_manager.py'],
                pathex=['C:\\Users\\Welaptega\\CMSv3\\app\\envs\\cms_env\\Lib\\site-packages',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\DLLs',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\lib',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38',
                        'C:\\Users\\Welaptega\\AppData\\Roaming\\Python\\Python38\\site-packages',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
cm_pyz = PYZ(cm_a.pure, cm_a.zipped_data,
             cipher=block_cipher)

cm_exe = EXE(cm_pyz,
          cm_a.scripts,
          [],
          exclude_binaries=True,
          name='client_manager',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )


dc_a = Analysis(['api\\server\\devices\\device_client.py'],
                pathex=['C:\\Users\\Welaptega\\CMSv3\\app\\envs\\cms_env\\Lib\\site-packages',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\DLLs',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\lib',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38',
                        'C:\\Users\\Welaptega\\AppData\\Roaming\\Python\\Python38\\site-packages',
                        'C:\\Users\\Welaptega\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
dc_pyz = PYZ(dc_a.pure, dc_a.zipped_data,
          cipher=block_cipher)

dc_exe = EXE(dc_pyz,
          dc_a.scripts,
          [],
          exclude_binaries=True,
          name='device_client',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )

coll = COLLECT(app_exe,
               app_a.binaries,
               app_a.zipfiles,
               app_a.datas,
               mc_exe,
               mc_a.binaries,
               mc_a.zipfiles,
               mc_a.datas,
               cm_exe,
               cm_a.binaries,
               cm_a.zipfiles,
               cm_a.datas,
               dc_exe,
               dc_a.binaries,
               dc_a.zipfiles,
               dc_a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='app')
